site_name: timechain.academy
site_url: https://timechain.academy
repo_url: https://github.com/timechain-academy/timechain.academy
docs_dir: sources
site_dir: docs

#REF: https://www.mkdocs.org/user-guide/configuration/
#REF: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections


use_directory_urls: true

nav:
    - :): 'README.md'
    - Setup: 'COMMANDS.md'
    - Plebnet Playground:
        - 'playground/docker/README.md'
        - make: 'playground/docker/MAKE.md'
        - play: 'playground/docker/PLAY.md'
        - More: 'playground/README.md'
    - Git:
        - 'git/README.md'
    - Gnupg: 'gnupg/README.md'
    - Qt: 'qt/README.md'
    - Bitcoin Script: 'ide/Readme.md'
    - LnBits: 'lnbits/lnbits.md'
    - Library:
        - Books: 'books/README.md'
        - Mastering Bitcoin:
            - Chapters:  'bitcoinbook/README.md'
            - Chapter 1: 'bitcoinbook/ch01.html'
            - Chapter 2: 'bitcoinbook/ch02.html'
            - Chapter 3: 'bitcoinbook/ch03.html'
            - Chapter 4: 'bitcoinbook/ch04.html'
            - Chapter 5: 'bitcoinbook/ch05.html'
            - Chapter 6: 'bitcoinbook/ch06.html'
            - Chapter 7: 'bitcoinbook/ch07.html'
            - Chapter 8: 'bitcoinbook/ch08.html'
            - Chapter 9: 'bitcoinbook/ch09.html'
            - Chapter 10: 'bitcoinbook/ch10.html'
            - Chapter 11: 'bitcoinbook/ch11.html'
            - Chapter 12: 'bitcoinbook/ch12.html'
            - Glossary: 'bitcoinbook/glossary.html'
        - Mastering Lighting: 'lnbook/README.md'
      # - Coarse Template: 'template/template.md'

plugins:
    - exclude:
        glob:
            - openpgp.org/vendor/bundle/**
            - "*.tmp"
            - "*.pdf"
            - "*.gz"
            - "*.asciidoc"
            - qt/webengine/*
            - qt/webengine/src/3rdparty/*
            - qt/webengine/src/3rdparty/*
            - FOOTER.md
            - HEADER.md
            - git/docs.md
            - awesome.md
            - ide/lib/ace/mode/_test/Readme.md
            - ide/lib/ace/mode/xquery/Readme.md
            - template/template.md
            - playground/docker/btcd/README.md
            - playground/docker/dashboard/README.md
            - playground/docker/docs/README.md
            - playground/docker/docs/docs/index.md
            - playground/docker/docs/docs/ALIASES.md
            - playground/docker/docs/docs/MAKE.md
            - playground/docker/docs/docs/PLAY.md
            - playground/docker/notebooks/README.md
            - playground/docker/scripts/README.md
            - playground/docker/worklogs/asherp.md
        regex:
            - '.*\.(tmp|bin|tar)$'
    - search
      # - redirects:
      #     redirect_maps:
      #         user-guide/plugins.md: dev-guide/plugins.md
      #         user-guide/custom-themes.md: dev-guide/themes.md
      #         user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md

markdown_extensions:
    - pymdownx.striphtml:
        strip_comments: true
        strip_js_on_attributes: false

copyright: Copyright &copy; 2022 <a href="https://twitter.com/RandyMcMillan">@RandyMcMillan</a>, Maintained by <a href="https://github.com/timechain-academy/timechain.academy/people">timechain.academy/people</a>.


# Development
watch:
    - sources
