site_name: timechain.academy
site_url: https://timechain.academy
repo_url: https://github.com/timechain-academy/timechain.academy
docs_dir: sources
site_dir: docs

#REF: https://www.mkdocs.org/user-guide/configuration/
#REF: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections


use_directory_urls: true

nav:
    - :): 'README.md'
    - Setup: 'COMMANDS.md'
    - Plebnet Playground:
        - 'playground/docker/README.md'
        - make: 'playground/docker/MAKE.md'
        - play: 'playground/docker/PLAY.md'
        - More: 'playground/README.md'
    - Git:
        - 'git/README.md'
    - Gnupg: 'gnupg/README.md'
    - Qt: 'qt/README.md'
    - Mastering Bitcoin: 'bitcoinbook/book.html'
    - Bitcoin Script: 'ide/Readme.md'
    - Mastering Lighting: 'lnbook/README.md'
    - LnBits: 'lnbits/lnbits.md'
      # - Coarse Template: 'template/template.md'

plugins:
    - exclude:
        glob:
            - openpgp.org/vendor/bundle/**
            - "*.tmp"
            - "*.pdf"
            - "*.gz"
            - "*.asciidoc"
            - qt/webengine/*
            - qt/webengine/src/3rdparty/*
            - qt/webengine/src/3rdparty/*
            - FOOTER.md
            - HEADER.md
            - git/docs.md
            - awesome.md
            - bitcoinbook/README.md
            - ide/lib/ace/mode/_test/Readme.md
            - ide/lib/ace/mode/xquery/Readme.md
            - lnbits/README.md
            - lnbook/CONTRIBUTING.md
            - lnbook/LICENSE.md
            - template/template.md
            - ide/CONTRIBUTING.md
            - ide/demo/kitchen-sink/docs/markdown.md
            - ide/doc/index.md
            - ide/tool/Readme.md
            - playground/docker/btcd/README.md
            - playground/docker/dashboard/README.md
            - playground/docker/docs/README.md
            - playground/docker/docs/docs/index.md
            - playground/docker/docs/docs/ALIASES.md
            - playground/docker/docs/docs/MAKE.md
            - playground/docker/docs/docs/PLAY.md
            - playground/docker/notebooks/README.md
            - playground/docker/scripts/README.md
            - playground/docker/worklogs/asherp.md
        regex:
            - '.*\.(tmp|bin|tar)$'
    - search
      # - redirects:
      #     redirect_maps:
      #         user-guide/plugins.md: dev-guide/plugins.md
      #         user-guide/custom-themes.md: dev-guide/themes.md
      #         user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md

markdown_extensions:
    - pymdownx.striphtml:
        strip_comments: true
        strip_js_on_attributes: false

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.


# Development
watch:
    - sources
